CREATE TABLE IF NOT EXISTS telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature FLOAT,
    humidity FLOAT, 
    ambient_light FLOAT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() 
);